config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only: %i(new create)
    resources :tours, only: %i(index show)
    resources :tour_requests, except: %i(new show edit)
    resources :reviews, only: :create
    namespace :admin do
      resources :users, only: %i(index edit update destroy)
      resources :tours
      resources :reviews
      resources :tour_requests
      resources :requests_histories
      get "/axlsx_index", to: "axlsx#index"
      resources :notifications
      get "/filter_ajax", to: "notifications#filter_ajax"
      resources :filter_tours, only: %i(index)
    end
    get "/authorization/:id", to: "authorizations#edit", as: :authorization
    post "/authorization/:id", to: "authorizations#update",
                               as: :authorization_activate
    mount ActionCable.server => "/cable"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/views/static_pages/home.html.erb
<div class="colorlib-loader"></div>
<div id="page">
  <aside id="colorlib-hero">
    <div class="flexslider">
      <ul class="slides">
        <li class="slides_1">
          <div class="overlay"></div>
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                <div class="slider-text-inner text-center">
                  <h1><%= t ".amazing_maldivest_tour" %></h1>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li class="slides_2">
          <div class="overlay"></div>
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                <div class="slider-text-inner text-center">
                  <h1><%= t ".from_greece_to_spain" %></h1>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li class="slides_3">
          <div class="overlay"></div>
          <div class="container-fluids">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                <div class="slider-text-inner text-center">
                  <h2><%= t ".explore_our_most_travel_agency" %></h2>
                  <h1><%= t ".our_travel_agency" %></h1>
                </div>
              </div>
            </div>
          </div>
        </li>
        <li class="slides_4">
          <div class="overlay"></div>
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                <div class="slider-text-inner text-center">
                  <h2><%= t ".experience_the" %></h2>
                  <h1><%= t ".best_trip_ever" %></h1>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </aside>
</div>
<div id="colorlib-services">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-3 animate-box text-center aside-stretch">
        <div class="services">
          <span class="icon">
            <i class="flaticon-around">
              <span class="iconify" data-icon="material-symbols:auto-awesome-outline" data-width="50" data-height="50"></span>
            </i>
          </span>
          <h3><%= t ".amazing_travel" %></h3>
          <p><%= t ".travel_description" %></p>
        </div>
      </div>
      <div class="col-md-3 animate-box text-center">
        <div class="services">
          <span class="icon">
            <i class="flaticon-boat">
              <span class="iconify" data-icon="ic:outline-tour" data-width="50" data-height="50"></span>
            </i>
          </span>
          <h3><%= t ".our_cruises" %></h3>
          <p><%= t ".travel_description" %></p>
        </div>
      </div>
      <div class="col-md-3 animate-box text-center">
        <div class="services">
          <span class="icon">
            <i class="flaticon-car">
              <span class="iconify" data-icon="icon-park-outline:tour-bus" data-width="50" data-height="50"></span>
            </i>
          </span>
          <h3><%= t ".book_your_trip" %></h3>
          <p><%= t ".travel_description" %></p>
        </div>
      </div>
      <div class="col-md-3 animate-box text-center">
        <div class="services">
          <span class="icon">
            <i class="flaticon-postcard">
              <span class="iconify" data-icon="fluent:person-support-16-regular" data-width="50" data-height="50"></span>
            </i>
          </span>
          <h3><%= t ".nice_support" %></h3>
          <p><%= t ".travel_description" %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="colorlib-tour colorlib-light-grey">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
        <h2><%= t ".popular_destination" %></h2>
        <p><%= t ".talk_destination" %></p>
      </div>
    </div>
  </div>
  <div class="tour-wrap">
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_1">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_2">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_3">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_4">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_5">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_6">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_7">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
    <a href="#" class="tour-entry animate-box">
      <div class="tour-img tour_8">
      </div>
      <span class="desc">
        <p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span></p>
      </span>
    </a>
  </div>
</div>
<div id="colorlib-testimony" class="colorlib-light-grey">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
        <h2><%= t ".guests_says" %></h2>
        <p><%= t ".talk_destination" %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 animate-box">
        <div class="owl-carousel2">
          <div class="item">
            <div class="testimony text-center">
              <span class="img-user img-user-1"></span>
              <span class="user"><%= t ".alysha_Myers" %></span>
              <small><%= t ".miami_Florida,_USA" %></small>
              <blockquote>
                <p><%= t ".guests_comments" %></p>
              </blockquote>
            </div>
          </div>
          <div class="item">
            <div class="testimony text-center">
              <span class="img-user img-user-2"></span>
              <span class="user"><%= t ".alysha_Myers" %></span>
              <small><%= t ".miami_Florida,_USA" %></small>
              <blockquote>
                <p><%= t ".guests_comments" %></p>
              </blockquote>
            </div>
          </div>
          <div class="item">
            <div class="testimony text-center">
              <span class="img-user img-user-3"></span>
              <span class="user"><%= t ".alysha_Myers" %></span>
              <small><%= t ".miami_Florida,_USA" %></small>
              <blockquote>
                <p><%= t ".guests_comments" %></p>
              </blockquote>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="colorlib-subscribe" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
        <h2><%= t ".sign_Up_Now" %></h2>
        <p><%= t ".singup_description" %></p>
        <%= link_to t(".signup"), signup_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/tour.html.erb
<div class="colorlib-loader"></div>
<div id="page">
  <aside id="colorlib-hero">
    <div class="flexslider">
      <ul class="slides">
        <li class= "tour_background">
          <div class="overlay"></div>
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                <div class="slider-text-inner text-center">
                  <h1><%= t ".find_Tours" %></h1>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </aside>
  <div class="colorlib-wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="wrap-division">
              <% if @tours.any? %>
                <%= render @tours %>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-center">
              <%== pagy_bootstrap_nav(@pagy) %>
            </div>
          </div>
        </div>
        <!-- SIDEBAR-->
        <div class="col-md-3">
          <div class="sidebar-wrap">
            <div class="side search-wrap animate-box">
              <h3 class="sidebar-heading"><%= t ".find_your_tour" %></h3>
              <%= form_tag(tour_path, method: :get, class: "colorlib-form") do %>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <%= label_tag :name, t(".name") %>
                      <div class="form-field">
                        <%= text_field_tag :name, "", class: "form-control", placeholder: t(".search_tour") %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <%= label_tag :start_date, t(".start_date") %>
                      <div class="form-field">
                        <%= date_field_tag :start_date, "", class: "form-control" %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <%= label_tag :end_date, t(".end_date") %>
                      <div class="form-field">
                        <%= date_field_tag :end_date, "", class: "form-control" %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <%= submit_tag t(".find_Tours"), class: "btn btn-primary btn-block" %>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="side animate-box">
              <div class="row">
                <div class="col-md-12">
                  <h3 class="sidebar-heading"><%= t ".price_Range" %></h3>
                  <form method="post" class="colorlib-form-2">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="guests"><%= t ".price_from" %></label>
                          <div class="form-field">
                            <i class="icon icon-arrow-down3"></i>
                            <select name="people" id="people" class="form-control">
                              <option value="#">1</option>
                            </select>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <label for="guests"><%= t ".price_to" %></label>
                          <div class="form-field">
                            <i class="icon icon-arrow-down3"></i>
                            <select name="people" id="people" class="form-control">
                              <option value="#">2000</option>
                            </select>
                          </div>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <div class="side animate-box">
              <div class="row">
                <div class="col-md-12">
                  <h3 class="sidebar-heading"><%= t ".review_Rating" %></h3>
                  <%= form_tag(tour_path, method: :get, class: "colorlib-form-2") do %>
                    <% temp = 5 %>
                    <% while temp > 0 %>
                      <div class="form-check">
                        <%= check_box_tag :rating_filter, class: "form-check-input" %>
                        <%= label_tag :rating_filter, "" do %>
                          <p class="rate"><span> <%= sanitize render_star(temp), attributes: %w(class data-icon) %> </span></p>
                        <% end %>
                      </div>
                      <% temp -= 1 %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>