config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only: %i(new create)
    resources :tours, only: %i(index show)
    resources :tour_requests, except: %i(new show edit)
    resources :reviews, only: :create
    namespace :admin do
      resources :users, only: %i(index edit update destroy)
      resources :tours
      resources :reviews
      resources :tour_requests
      resources :requests_histories
      get "/axlsx_index", to: "axlsx#index"
      resources :notifications
      get "/filter_ajax", to: "notifications#filter_ajax"
      resources :filter_tours, only: %i(index)
    end
    get "/authorization/:id", to: "authorizations#edit", as: :authorization
    post "/authorization/:id", to: "authorizations#update",
                               as: :authorization_activate
    mount ActionCable.server => "/cable"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/tour.rb
class Tour < ApplicationRecord
  UPDATABLE_ATTRS = %i(name description price start_date end_date
                       avg_rating category_id stock).freeze

  has_many :tour_requests, dependent: :destroy
  has_many :discounts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :category
  has_many :reviews, dependent: :destroy
  # after_update :send_email_update_tour

  has_one_attached :image

  delegate :name, to: :category, prefix: true

  validates :name, presence: true,
                        length: {maximum: Settings.tour.name_max}
  validates :description, presence: true,
                               length: {maximum: Settings.tour.description_max}
  validates :start_date, :end_date, presence: true
  validates :price, presence: true,
                            numericality: {
                              greater_than_or_equal_to:
                               Settings.tour.quantity_min
                            }
  validates :stock, presence: true,
                            numericality: {
                              greater_than_or_equal_to:
                               Settings.tour.stock_min
                            }
  validates :avg_rating, presence: true,
                         numericality: {
                           greater_than_or_equal_to:
                           Settings.tour.rating_min,
                           smaller_than_or_equal_to:
                          Settings.tour.rating_max
                         }
  validates :image, content_type: {in: Settings.tour.image_type,
                                   message: :mess},
                    size: {
                      less_than: Settings.tour.image_size.megabytes,
                      message: :size_img
                    }

  scope :incre_order, ->{order(id: :asc)}
  scope :order_rating, (lambda do |rating|
    where("avg_rating = ?", rating)
  end)
  scope :recent_tours, ->{order(created_at: :desc)}
  scope :by_start_date, (lambda do |start_date|
    where("start_date >= ?", start_date) if start_date.present?
  end)
  scope :by_end_date, (lambda do |end_date|
    where("end_date <= ?", end_date) if end_date.present?
  end)
  scope :by_most_name, (lambda do |name|
    where("name LIKE ?", "%#{name}%") if name.present?
  end)
  scope :by_start_date, (lambda do |start_date|
    where("start_date >= ?", start_date) if start_date.present?
  end)
  scope :by_end_date, (lambda do |end_date|
    where("end_date <= ?", end_date) if end_date.present?
  end)
  scope :by_most_name, (lambda do |name|
    where("name LIKE ?", "%#{name}%") if name.present?
  end)
  scope :by_rating_array, (lambda do |get_rating|
    where(avg_rating: get_rating) if get_rating.present?
  end)

  scope :select_col, (lambda do |col|
    select(col) if col.present?
  end)

  scope :join_tbl, (lambda do |tbl|
    joins(tbl) if col.present?
  end)

  scope :by_start_price, (lambda do |start_price|
    where("price >= ?", start_price) if start_price.present?
  end)

  scope :by_end_price, (lambda do |end_price|
    where("price <= ?", end_price) if end_price.present?
  end)

  scope :by_avg_ratings, (lambda do |avg_ratings|
    where("avg_rating <= ?", avg_ratings) if avg_ratings.present?
  end)

  scope :order_by_name, (lambda do |order_by|
    order(name: order_by) if order_by.present?
  end)

  scope :order_by_price, (lambda do |order_by|
    order(price: order_by) if order_by.present?
  end)
  scope :by_rating_array, (lambda do |get_rating|
    where(avg_rating: get_rating) if get_rating.present?
  end)

  scope :select_col, (lambda do |col|
    select(col) if col.present?
  end)

  scope :join_tbl, (lambda do |tbl|
    joins(tbl) if col.present?
  end)

  def display_image
    image.variant resize_to_limit:
    [
      Settings.tour.height_limit,
      Settings.tour.width_limit
    ]
  end

  def self.search start_date, end_date, start_price, end_price,
    avg_rating, name_like, order_name, order_price

    @tours = Tour.by_start_date(start_date)
                 .by_end_date(end_date)
                 .by_start_price(start_price)
                 .by_end_price(end_price)
                 .by_avg_ratings(avg_rating)
                 .by_most_name(name_like)
                 .order_by_price(order_price)
                 .order_by_name(order_name)
    @tours
  end

  def send_email_update_tour
    TourMailer.send_update_tour self
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  layout "layouts/application_admin"
  before_action :logged_in_user
  before_action :check_admin
  before_action :load_tour, except: %i(create new index)
  before_action :check_tour_update, only: %i(update edit)

  def index
    @pagy, @tours = pagy(Tour.recent_tours, items: Settings.tour.per_page_admin)
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new tour_params

    if @tour.save
      flash[:success] = t ".tours_create_successful"
      redirect_to admin_tours_path
    else
      flash[:danger] = t ".tours_not_saved"
      render :new
    end
  end

  def show
    @pagy, @reviews = pagy(@tour.reviews.most_recent,
                           items: Settings.review.admin_per_page)
  end

  def edit
    if @tour.start_date > Time.zone.now
      flash.now[:success] = t ".edit_success"
    else
      flash[:danger] = t ".edit_failed"
      redirect_to admin_tours_path
    end
  end

  def update
    if @tour.update tour_params
      success_format t ".update_success"
    else
      danger_format t ".update_failed"
    end
  end

  def destroy
    total = Tour.all.count
    index = Tour.all.find_index(@tour)
    if @tour.destroy
      cur_page = handle_page total, index
      @pagy, @tours = pagy(Tour.recent_tours,
                           items: Settings.tour.per_page_admin, page: cur_page)
      success_format t ".destroy_success"
    else
      @pagy, @tours = pagy(Tour.recent_tours,
                           items: Settings.tour.per_page_admin)
      danger_format t ".destroy_danger"
    end
  end

  private

  def handle_page total, index
    cur_page = (((total - index) - 1) / Settings.tour.per_page_admin).ceil + 1

    tours = Tour.limit(Settings.tour.per_page_admin).offset(
      Settings.tour.per_page_admin * (cur_page - 1)
    )
    cur_page -= 1 if tours.empty?
    cur_page
  end

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour

    flash[:danger] = t ".show_tour_failed"
    redirect_to admin_tours_path
  end

  def tour_params
    params.require(:tour).permit Tour::UPDATABLE_ATTRS
  end

  def check_tour_update
    if @tour.start_date >= Time.current
      flash.now[:success] = t ".edit_success"
    else
      flash[:danger] = t ".edit_failed"
      redirect_to admin_tours_path
    end
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_tour, :load_comments, only: :show
  before_action :gen_filter_rating, :filter_tour, only: :index

  def show; end

  def index
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def find_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour

    flash[:danger] = t ".can_not_find_tour"
    redirect_to root_path
  end

  def load_comments
    @pagy, @reviews = pagy @tour.reviews.most_recent,
                           items: Settings.review.review_per_page,
                           link_extra: 'data-remote="true"'
  end

  def gen_filter_rating
    @rating_filter = []
    (0..Settings.review.rating_max).each do |i|
      rating = params["rating_filter_#{i}"]
      @rating_filter[i] = rating if rating.present?
    end

    @rating_filter.map!.with_index do |value, index|
      index if value == "1"
    end
  end

  def filter_tour
    @pagy, @tours = pagy Tour.by_most_name(params.dig(:search, :name))
                             .by_start_date(params.dig(:search, :start_date))
                             .by_end_date(params.dig(:search, :end_date))
                             .by_rating_array(@rating_filter)
                             .recent_tours,
                         items: Settings.tour.tour_per_page,
                         link_extra: 'data-remote="true"'
  end
end

app/helpers/tours_helper.rb
module ToursHelper
  def render_star star
    temp = ""
    stared = star.to_i
    stared.times do
      temp += '<i class="iconify icon-star-full"
              data-icon="icomoon-free:star-full"></i>'
    end

    (Settings.tour.rating_max - stared).times do
      temp += '<i class="iconify icon-star-empty"
              data-icon="icomoon-free:star-empty"></i>'
    end
    temp
  end

  def date_diff start_date, end_date
    (end_date.to_date - start_date.to_date).to_i
  end

  def render_star_form
    temp = ""
    Settings.review.rating_max.downto(1) do |i|
      temp += "<i class='iconify icon-star-empty-form'
              data-icon='icomoon-free:star-empty' data-star='#{i}'></i>"
    end
    temp
  end

  def check_view_edit tour
    return unless tour.start_date >= Time.current

    link_to "<i class='nc-icon nc-ruler-pencil text-success m-2'></i>",
            edit_admin_tour_path(tour.id)
  end
end

app/views/admin/tours/_form.html.erb
<div class="form_tour">
  <%= form_for [:admin, @tour], remote: true do |f| %>
    <%= render "layouts/error_messages", object: f.object %>
    <div class="col-12">
      <div class="content">
        <div class="row">
          <div class="col-md-4">
            <div class="card card-user">
              <div class="image">
              </div>
              <div class="card-body">
                <div class="author">
                  <div class="row form-group">
                    <div class="col-md-12">
                      <%= f.label t(".image") %>
                      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
                      <%= image_tag @tour.display_image, class: "hotel-img tour__preview"  if @tour.image.attached? %>
                      <img class="tour__preview" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="card card-user">
              <div class="card-header">
                <h5 class="card-title"><%= yield(:button_text) %></h5>
              </div>
              <div class="card-body">
                <form>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label><%= t ".name" %></label>
                        <%= f.text_field :name, class: "form-control", placeholder:  t(".name") %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label><%= t ".price" %></label>
                        <%= f.text_field :price, class: "form-control", placeholder: t(".price") %>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="exampleInputEmail1"><%= t ".category" %></label>
                        <%= f.select :category_id, load_category,  {}, {class: "form-control"} %>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6 pr-1">
                      <div class="form-group">
                        <label><%= t ".start_date" %></label>
                        <%= f.date_field :start_date, class: "form-control", placeholder: t(".start_date") %>
                      </div>
                    </div>
                    <div class="col-md-6 pl-1">
                      <div class="form-group">
                        <label><%= t ".end_date" %></label>
                        <%= f.date_field :end_date, class: "form-control", placeholder: t(".end_date") %>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <% if @tour.present? %>
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label t(".avg_rating") %>
                          <div>
                            <%= sanitize render_star(@tour.avg_rating), attributes: %w(class data-icon) %>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label><%= t ".description" %></label>
                        <%= f.text_field :description, class: "form-control", placeholder: t(".description") %>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="update ml-auto mr-auto">
                      <%= f.submit yield(:button_text), class: "btn btn-primary btn-round" %>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/tours/_navbar.html.erb
<div class="row">
  <%= form_tag admin_tours_filter_path ,method: :get, remote: true do %>
    <div class="col-md-6">
      <div class="form-group search_name">
        <div class="flex-container">
          <%= text_field_tag :name_like, nil, class: "form-control", placeholder: "Your tour's name" %>
          <%= button_tag(type: "submit") do %>
            <span class="iconify" data-icon="bi:search-heart"></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <%= form_tag admin_tours_filter_path, method: :get, remote: true do %>
    <div class="col-md-6">
      <div class="form-group search_name">
        <div class="flex-container">
          <%= select_tag(:order_tours_admin, options_for_select([[Settings.admin.tour.name.asc,1],[Settings.admin.tour.name.desc,2],[Settings.admin.tour.price.asc,3],[Settings.admin.tour.price.desc,4]]), class:"form-control") %>
          <%= button_tag(type: "submit") do %>
            <span class="iconify" data-icon="bxs:sort-alt"></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/tours/_search_form.html.erb
<div class="search_admin_form">
  <div class="container-fluid mx-auto">
    <div class="row d-flex w-100 ">
      <div class="col-12">
        <div class="card border-0">
          <%= form_tag admin_filter_tours_path ,method: :get, remote: true do %>
            <div class="card-body px-3 px-md-5">
              <div class="card mb-3">
                <div class="card-body">
                  <%= text_field_tag :name_like, nil, placeholder: "Your tour's name" %>
                </div>
              </div>
              <div class="card mb-3">
                <div class="row">
                  <div class="col-md-6">
                    <div class="card-header">
                      <h6><span class="fa fa-calendar mr-3"></span><%= t ".ariving_date" %></h6>
                    </div>
                    <div class="card-body">
                      <div class="row px-4">
                        <div class="col-6 col-lg-3 text-center px-0 arrival active">
                          <div class="block py-1"><%= t ".specific" %></div>
                        </div>
                        <div class="col-6 col-lg-3 text-center px-0 arrival">
                          <div class="block py-1"><%= t ".after" %></div>
                        </div>
                        <div class="col-6 col-lg-3 text-center px-0 arrival">
                          <div class="block py-1"><%= t ".before" %></div>
                        </div>
                        <div class="col-6 col-lg-3 text-center px-0 arrival">
                          <div class="block py-1"><%= t ".between" %></div>
                        </div>
                      </div>
                      <div class="row px-4 mt-3">
                        <div class="col-md-6 pl-0 pr-0 pr-md-2 mb-2">
                          <%= date_field_tag :start_date %>
                        </div>
                        <div class="col-md-6 pl-0 pl-md-2 pr-0">
                          <%= date_field_tag :end_date %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="card-header">
                      <h6><span class="fa fa-star icon-star mr-3"></span><%= t ".choose_star" %></h6>
                    </div>
                    <div class="card-body">
                      <div class="row px-4 mb-2">
                        <div class="col-4 text-center px-0 hotel active">
                          <div class="block py-1"><%= t ".equals" %></div>
                        </div>
                        <div class="col-4 text-center px-0 hotel">
                          <div class="block py-1"><%= t ".less" %></div>
                        </div>
                        <div class="col-4 text-center px-0 hotel">
                          <div class="block py-1"><%= t ".more" %></div>
                        </div>
                      </div>
                      <div class="row px-4">
                        <div class="form-group star">
                          <% Settings.tour.rating_max.times do |n| %>
                            <div class="form-star">
                              <%= check_box_tag 'avg_ratings[]',n + 1, nil, :id => "admin_tour_star_#{n + 1}"  %>
                              <i class="iconify icon-star-empty"
                                  data-icon="icomoon-free:star-empty" id="icon_tour_star_<%= n + 1 %>"></i>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="card-header">
                      <h6><span class="fa fa-star icon-star mr-3"></span><%= t ".choose_price" %></h6>
                    </div>
                    <div class="card-body">
                      <div class="row px-4 mb-2">
                        <div class="col-4 text-center px-0 hotel active">
                          <div class="block py-1"><%= t ".equals" %></div>
                        </div>
                        <div class="col-4 text-center px-0 hotel">
                          <div class="block py-1"><%= t ".less" %></div>
                        </div>
                        <div class="col-4 text-center px-0 hotel">
                          <div class="block py-1"><%= t ".more" %></div>
                        </div>
                      </div>
                      <div class="row px-4">
                        <div class="col-md-6 pl-0 pr-0 pr-md-2 mb-2">
                          <%= text_field_tag :start_price, nil, placeholder: t(".start_date") %>
                        </div>
                        <div class="col-md-6 pl-0 pl-md-2 pr-0">
                          <%= text_field_tag :end_price, nil, placeholder: t(".end_date") %>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="card-header">
                      <h6><span class="fa fa-star icon-star mr-3"></span><%= t ".sort" %></h6>
                    </div>
                    <div class="card-body">
                      <div class="row px-4">
                        <%= select_tag(:order_tours_admin, options_for_select([[t(".name_asc"),1],[t(".name_desc"),2],[t(".price_asc"),3],[t(".price_desc"),4]]), class:"form-control") %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row px-3">
                <p id="green" class="mr-2"><span class="mr-2 fa fa-plus"></span><%= t ".and" %></p>
                <p id="blue"><span class="mr-2 fa fa-reorder"></span><%= t ".or" %></p>
              </div>
            </div>
            <div class="card-footer bg-white row mx-0 mb-2 justify-content-between">
              <button class="btn btn-secondary px-4"><%= t ".cancel" %></button>
              <button type="submit" class="btn btn-success ml-auto"><span class="iconify" data-icon="akar-icons:search"></span> &nbsp;&nbsp;<%= t ".filter" %></button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/tours/_sidebar.html.erb
<div class="sidebar-wrap">
  <div class="side search-wrap animate-box">
    <h3 class="sidebar-heading">Find your hotel</h3>
    <%= form_for :tours_filter, url: admin_tours_filter_url , method: :get, class: "colorlib-form", remote: true do |f| %>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <p for="date">Check-in:</p>
            <div class="form-field">
              <i class="icon icon-calendar2"></i>
              <%= f.date_field :start_date, class: "form-control"%>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="form-group">
            <p for="date">Check-out:</p>
            <div class="form-field">
              <i class="icon icon-calendar2"></i>
              <%= f.date_field :end_date, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <p for="guests">Price from</p>
            <div class="form-field">
              <i class="icon icon-arrow-down3"></i>
              <%= f.text_field :start_price, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <p for="guests">Price to</p>
            <div class="form-field">
              <i class="icon icon-arrow-down3"></i>
              <%= f.text_field :start_price, class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="form-group star">
            <% Settings.tour.rating_max.times do |n| %>
              <div class="form-star">
                <%= check_box_tag 'avg_ratings[]',n + 1, nil, :id => "admin_tour_star_#{n + 1}"  %>
                <i class="iconify icon-star-empty"
              data-icon="icomoon-free:star-empty" id="icon_tour_star_<%= n + 1 %>"></i>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-md-12">
          <%= f.submit "Filter", class: "btn btn-lg btn-success" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/admin/tours/_tour._detail.html.erb
<div class="col-md-6 col-sm-6 animate-box" id="tour_<%= tour.id %>">
  <div class="hotel-entry">
    <%= link_to admin_tour_path(tour.id) do %>
      <%= image_tag tour.display_image, class: "hotel-img"  if tour.image.attached? %>
      <p class="price"><span>$<%= tour.price %></span><small> <%= t ".night" %></small></p>
    <% end %>
    <div class="desc">
      <p class="star">
        <span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span>
        <%= tour.reviews.count %> <%= t ".reviews" %>
      </p>
      <%= sanitize render_star(tour.avg_rating), attributes: %w(class data-icon) %>
      <h3><a href="hotel-room.html"><%= tour.name %></a></h3>
      <span class="place"><%= tour.category.name %></span>
      <p class="description">
        <%= tour.description %>
      </p>
    </div>
    <div class="flex-container">
      <%= link_to edit_admin_tour_path(tour), class:"text-info" do %>
        <i class="fas fa-pencil-alt"></i>
      <% end %>
      <%= link_to admin_tour_path(tour), method: :delete, data: {confirm: t(".delete")}, class: "text-danger", remote: true do %>
        <i class="far fa-trash-alt"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/tours/_tour.html.erb
<tr>
  <td><input type="checkbox" class="checkthis" /></td>
  <td><%= tour.name %></td>
  <td><%= tour.price %></td>
  <td> <%= sanitize render_star(tour.avg_rating), attributes: %w(class data-icon) %></td>
  <td><%=  tour.start_date %></td>
  <td><%=  tour.end_date %></td>
  <td><%= tour.category_name %></td>
  <td><%= tour.stock %></td>
  <td>
    <%= link_to admin_tour_path(tour.id) do %>
      <span class="iconify nc-icon text-primary m-2"  data-icon="bx:show"></span>
    <% end %>
    <%= check_view_edit tour %>
    <%= link_to admin_tour_path(tour.id), method: :delete, data: {confirm: t(".delete")}, class: "text-danger", remote: true do %>
      <i class="nc-icon nc-simple-remove text-danger"></i>
    <% end %>
  </td>
</tr>

app/views/admin/tours/destroy.js.erb
$('#flash').html('<%= j render "layouts/flash_messages", flash: flash %> ');
$('#list_tours').html('<%= j render @tours %>');
$('#list_tours_pagy').html('<%== pagy_bootstrap_nav(@pagy) %>');

app/views/admin/tours/edit.html.erb
<% provide(:button_text, t(".button_text")) %>
<%= render "form" %>

app/views/admin/tours/filter_tour.js.erb
$('#flash').html('<%= j render "layouts/flash_messages", flash: flash %> ');
$('#list_tours').html('<%= j render @tours %>');
$('#list_tours_pagy').html('<%== pagy_bootstrap_nav(@pagy) %>');

app/views/admin/tours/index.html.erb
<div class="col-md-12">

<%= render "search_form" %>
<div class="list_tours">
        <table id="mytable" class="table table-bordred table-striped">
          <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th><%= t ".name" %></th>
            <th><%= t ".price" %></th>
            <th><%= t ".ratings" %></th>
            <th><%= t ".start_date" %></th>
            <th><%= t ".end_date" %></th>
            <th><%= t ".category" %></th>
            <th><%= t ".stock" %></th>
            <th><%= t ".action" %></th>
          </thead>
          <tbody id="list_tours">
            <%= render @tours %>
          </tbody>
        </table>
  <div id="list_tours_pagy">
    <%== pagy_bootstrap_nav @pagy %>
  </div>
</div>
</div>

app/views/admin/tours/new.html.erb
<% provide(:button_text, t(".button_text")) %>
<%= render "form" %>

app/views/admin/tours/update.js.erb
$('#flash').html('<%= j render "layouts/flash_messages", flash: flash %> ');
<% provide(:button_text, "Edit") %>
$('#tour_form').html('<%= j render "form" %>');