config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only: %i(new create)
    resources :tours, only: %i(index show)
    resources :tour_requests, except: %i(new show edit)
    resources :reviews, only: :create
    namespace :admin do
      resources :users, only: %i(index edit update destroy)
      resources :tours
      resources :reviews
      resources :tour_requests
      resources :requests_histories
      get "/axlsx_index", to: "axlsx#index"
      resources :notifications
      get "/filter_ajax", to: "notifications#filter_ajax"
      resources :filter_tours, only: %i(index)
    end
    get "/authorization/:id", to: "authorizations#edit", as: :authorization
    post "/authorization/:id", to: "authorizations#update",
                               as: :authorization_activate
    mount ActionCable.server => "/cable"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/tour.rb
class Tour < ApplicationRecord
  UPDATABLE_ATTRS = %i(name description price start_date end_date
                       avg_rating category_id stock).freeze

  has_many :tour_requests, dependent: :destroy
  has_many :discounts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :category
  has_many :reviews, dependent: :destroy
  # after_update :send_email_update_tour

  has_one_attached :image

  delegate :name, to: :category, prefix: true

  validates :name, presence: true,
                        length: {maximum: Settings.tour.name_max}
  validates :description, presence: true,
                               length: {maximum: Settings.tour.description_max}
  validates :start_date, :end_date, presence: true
  validates :price, presence: true,
                            numericality: {
                              greater_than_or_equal_to:
                               Settings.tour.quantity_min
                            }
  validates :stock, presence: true,
                            numericality: {
                              greater_than_or_equal_to:
                               Settings.tour.stock_min
                            }
  validates :avg_rating, presence: true,
                         numericality: {
                           greater_than_or_equal_to:
                           Settings.tour.rating_min,
                           smaller_than_or_equal_to:
                          Settings.tour.rating_max
                         }
  validates :image, content_type: {in: Settings.tour.image_type,
                                   message: :mess},
                    size: {
                      less_than: Settings.tour.image_size.megabytes,
                      message: :size_img
                    }

  scope :incre_order, ->{order(id: :asc)}
  scope :order_rating, (lambda do |rating|
    where("avg_rating = ?", rating)
  end)
  scope :recent_tours, ->{order(created_at: :desc)}
  scope :by_start_date, (lambda do |start_date|
    where("start_date >= ?", start_date) if start_date.present?
  end)
  scope :by_end_date, (lambda do |end_date|
    where("end_date <= ?", end_date) if end_date.present?
  end)
  scope :by_most_name, (lambda do |name|
    where("name LIKE ?", "%#{name}%") if name.present?
  end)
  scope :by_start_date, (lambda do |start_date|
    where("start_date >= ?", start_date) if start_date.present?
  end)
  scope :by_end_date, (lambda do |end_date|
    where("end_date <= ?", end_date) if end_date.present?
  end)
  scope :by_most_name, (lambda do |name|
    where("name LIKE ?", "%#{name}%") if name.present?
  end)
  scope :by_rating_array, (lambda do |get_rating|
    where(avg_rating: get_rating) if get_rating.present?
  end)

  scope :select_col, (lambda do |col|
    select(col) if col.present?
  end)

  scope :join_tbl, (lambda do |tbl|
    joins(tbl) if col.present?
  end)

  scope :by_start_price, (lambda do |start_price|
    where("price >= ?", start_price) if start_price.present?
  end)

  scope :by_end_price, (lambda do |end_price|
    where("price <= ?", end_price) if end_price.present?
  end)

  scope :by_avg_ratings, (lambda do |avg_ratings|
    where("avg_rating <= ?", avg_ratings) if avg_ratings.present?
  end)

  scope :order_by_name, (lambda do |order_by|
    order(name: order_by) if order_by.present?
  end)

  scope :order_by_price, (lambda do |order_by|
    order(price: order_by) if order_by.present?
  end)
  scope :by_rating_array, (lambda do |get_rating|
    where(avg_rating: get_rating) if get_rating.present?
  end)

  scope :select_col, (lambda do |col|
    select(col) if col.present?
  end)

  scope :join_tbl, (lambda do |tbl|
    joins(tbl) if col.present?
  end)

  def display_image
    image.variant resize_to_limit:
    [
      Settings.tour.height_limit,
      Settings.tour.width_limit
    ]
  end

  def self.search start_date, end_date, start_price, end_price,
    avg_rating, name_like, order_name, order_price

    @tours = Tour.by_start_date(start_date)
                 .by_end_date(end_date)
                 .by_start_price(start_price)
                 .by_end_price(end_price)
                 .by_avg_ratings(avg_rating)
                 .by_most_name(name_like)
                 .order_by_price(order_price)
                 .order_by_name(order_name)
    @tours
  end

  def send_email_update_tour
    TourMailer.send_update_tour self
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < ApplicationController
  layout "layouts/application_admin"
  before_action :logged_in_user
  before_action :check_admin
  before_action :load_tour, except: %i(create new index)
  before_action :check_tour_update, only: %i(update edit)

  def index
    @pagy, @tours = pagy(Tour.recent_tours, items: Settings.tour.per_page_admin)
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new tour_params

    if @tour.save
      flash[:success] = t ".tours_create_successful"
      redirect_to admin_tours_path
    else
      flash[:danger] = t ".tours_not_saved"
      render :new
    end
  end

  def show
    @pagy, @reviews = pagy(@tour.reviews.most_recent,
                           items: Settings.review.admin_per_page)
  end

  def edit
    if @tour.start_date > Time.zone.now
      flash.now[:success] = t ".edit_success"
    else
      flash[:danger] = t ".edit_failed"
      redirect_to admin_tours_path
    end
  end

  def update
    if @tour.update tour_params
      success_format t ".update_success"
    else
      danger_format t ".update_failed"
    end
  end

  def destroy
    total = Tour.all.count
    index = Tour.all.find_index(@tour)
    if @tour.destroy
      cur_page = handle_page total, index
      @pagy, @tours = pagy(Tour.recent_tours,
                           items: Settings.tour.per_page_admin, page: cur_page)
      success_format t ".destroy_success"
    else
      @pagy, @tours = pagy(Tour.recent_tours,
                           items: Settings.tour.per_page_admin)
      danger_format t ".destroy_danger"
    end
  end

  private

  def handle_page total, index
    cur_page = (((total - index) - 1) / Settings.tour.per_page_admin).ceil + 1

    tours = Tour.limit(Settings.tour.per_page_admin).offset(
      Settings.tour.per_page_admin * (cur_page - 1)
    )
    cur_page -= 1 if tours.empty?
    cur_page
  end

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour

    flash[:danger] = t ".show_tour_failed"
    redirect_to admin_tours_path
  end

  def tour_params
    params.require(:tour).permit Tour::UPDATABLE_ATTRS
  end

  def check_tour_update
    if @tour.start_date >= Time.current
      flash.now[:success] = t ".edit_success"
    else
      flash[:danger] = t ".edit_failed"
      redirect_to admin_tours_path
    end
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_tour, :load_comments, only: :show
  before_action :gen_filter_rating, :filter_tour, only: :index

  def show; end

  def index
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def find_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour

    flash[:danger] = t ".can_not_find_tour"
    redirect_to root_path
  end

  def load_comments
    @pagy, @reviews = pagy @tour.reviews.most_recent,
                           items: Settings.review.review_per_page,
                           link_extra: 'data-remote="true"'
  end

  def gen_filter_rating
    @rating_filter = []
    (0..Settings.review.rating_max).each do |i|
      rating = params["rating_filter_#{i}"]
      @rating_filter[i] = rating if rating.present?
    end

    @rating_filter.map!.with_index do |value, index|
      index if value == "1"
    end
  end

  def filter_tour
    @pagy, @tours = pagy Tour.by_most_name(params.dig(:search, :name))
                             .by_start_date(params.dig(:search, :start_date))
                             .by_end_date(params.dig(:search, :end_date))
                             .by_rating_array(@rating_filter)
                             .recent_tours,
                         items: Settings.tour.tour_per_page,
                         link_extra: 'data-remote="true"'
  end
end

app/helpers/tours_helper.rb
module ToursHelper
  def render_star star
    temp = ""
    stared = star.to_i
    stared.times do
      temp += '<i class="iconify icon-star-full"
              data-icon="icomoon-free:star-full"></i>'
    end

    (Settings.tour.rating_max - stared).times do
      temp += '<i class="iconify icon-star-empty"
              data-icon="icomoon-free:star-empty"></i>'
    end
    temp
  end

  def date_diff start_date, end_date
    (end_date.to_date - start_date.to_date).to_i
  end

  def render_star_form
    temp = ""
    Settings.review.rating_max.downto(1) do |i|
      temp += "<i class='iconify icon-star-empty-form'
              data-icon='icomoon-free:star-empty' data-star='#{i}'></i>"
    end
    temp
  end

  def check_view_edit tour
    return unless tour.start_date >= Time.current

    link_to "<i class='nc-icon nc-ruler-pencil text-success m-2'></i>",
            edit_admin_tour_path(tour.id)
  end
end

app/views/tours/_booking.html.erb
<%= form_for current_user.tour_requests.build, remote: true do |f| %>
  <%= f.hidden_field :tour_id, value: @tour.id %>
  <div class="col-md-3">
    <div class="form-group">
      <div class="form-field">
        <span> <%= t ".quantity" %> </span>
        <%= f.text_field :quantity, class: "form-control", value: Settings.tour.default_quantity %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="form-group">
      <div class="form-field">
        <span> <%= t ".total_price" %> </span>
        <%= f.text_field :total_price, class: "form-control", value: @tour.price, readonly: true %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="form-group">
      <div class="form-field">
        <%= f.submit t(".submit"), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/tours/_tour.html.erb
<div class="col-md-6 col-sm-6 animate-box">
  <div class="tour">
    <%= link_to tour_path(tour), class:"tour-img" do %>
      <%= image_tag tour.image %>
      <p class="price">
        <span><%= number_to_currency tour.price %></span>
        <small>/ <%= date_diff tour.start_date, tour.end_date %> <%= t(".day") %></small>
      </p>
    <% end %>
    <span class="desc">
      <p class="star"><span> <%= sanitize render_star(tour.avg_rating), attributes: %w(class data-icon) %> </span></p>
      <h2><%= link_to tour.name, tour_path(tour) %></h2>
      <span class="city"><%= tour.description %></span>
    </span>
  </div>
</div>

app/views/tours/index.html.erb
<div class="colorlib-loader"></div>
<div id="page">
  <aside id="colorlib-hero">
    <div class="flexslider">
      <ul class="slides">
        <li class= "tour_background">
          <div class="overlay"></div>
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                <div class="slider-text-inner text-center">
                  <h1><%= t ".find_Tours" %></h1>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </aside>
  <div class="colorlib-wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <div class="wrap-division">
              <div id="container">
                <% if @tours.any? %>
                  <%= render @tours %>
                <% else %>
                  <h1><%= t ".no_tours" %></h1>
                <% end %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-center">
              <div id="pagy_container">
                <%== pagy_bootstrap_nav_js @pagy %>
              </div>
            </div>
          </div>
        </div>
        <!-- SIDEBAR-->
        <div class="col-md-3">
          <div class="sidebar-wrap">
            <%= form_tag(tours_path, method: :get, class: "colorlib-form", id: "search-form", remote: true) do %>
              <div class="side search-wrap animate-box">
                <h3 class="sidebar-heading"><%= t ".find_your_tour" %></h3>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <%= label_tag :name, t(".name") %>
                      <div class="form-field">
                        <%= text_field_tag "search[name]", "", class: "form-control", placeholder: t(".search_tour") %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <%= label_tag :start_date, t(".start_date") %>
                      <div class="form-field">
                        <%= date_field_tag "search[start_date]", "", class: "form-control" %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <%= label_tag :end_date, t(".end_date") %>
                      <div class="form-field">
                        <%= date_field_tag "search[end_date]", "", class: "form-control" %>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <%= submit_tag t(".find_Tours"), class: "btn btn-primary btn-block" %>
                  </div>
                </div>
              </div>
              <div class="side animate-box">
                <div class="row">
                  <div class="col-md-12">
                    <h3 class="sidebar-heading"><%= t ".review_Rating" %></h3>
                    <% for i in 0..5 do %>
                      <div class="form-check">
                        <%= check_box_tag "rating_filter_#{Settings.tour.rating_max-i}", 1, checked: true %>
                        <%= label_tag "rating_filter_#{Settings.tour.rating_max-i}", "" do %>
                          <p class="rate rating-star"><span> <%= sanitize render_star(Settings.tour.rating_max-i), attributes: %w(class data-icon) %> </span></p>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tours/index.js.erb
<% if @tours.empty? %>
  $('#container').html('<h1><%= t ".no_tours" %></h1>');
  $('#pagy_container').html("");
<% else %>
  $('#container').html("<%= j render @tours %>");
  $('#pagy_container').html('<%== pagy_bootstrap_nav_js @pagy %>');
  Pagy.init($('#container'));
  Pagy.init($('#pagy_container'));
<% end %>

app/views/tours/show.html.erb
<div class="colorlib-loader"></div>
<div id="page">
  <aside id="colorlib-hero">
    <div class="flexslider">
      <ul class="slides">
        <li class="tourshow_background">
          <div class="overlay"></div>
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12 slider-text">
                <div class="slider-text-inner text-center">
                  <h1><%= t ".find_Tours" %></h1>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </aside>
  <div class="colorlib-wrap">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12">
              <div class="wrap-division">
                <div class="col-md-12 col-md-offset-0 heading2 animate-box">
                  <h2><%= @tour.name %></h2>
                </div>
                <div class="row">
                  <div class="col-md-12 animate-box">
                    <div class="room-wrap">
                      <div class="row">
                        <div class="col-md-6 col-sm-6">
                          <div class="room-img">
                            <%= image_tag @tour.image %>
                          </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                          <div class="desc">
                            <p class="star"><span> <%= sanitize render_star(@tour.avg_rating), attributes: %w(class data-icon) %> </span></p>
                            <h2><%= @tour.description %></h2>
                            <div class="row">
                              <p class="price col-sm-6">
                                <span><%= number_to_currency @tour.price %></span>
                                <small> / <%= date_diff @tour.start_date, @tour.end_date %> <%= t(".day") %></small>
                              </p>
                              <h4 class="col-sm-6 stock"><%= t ".stock" %> <span id="tour_stock"><%= @tour.stock %></span></h4>
                            </div>
                            <div class="col-md-6">
                              <div class="form-group">
                                <div class="form-field">
                                  <span> <%= t ".start_date" %> </span>
                                  <%= date_field :start_date, "", class: "form-control", value: @tour.start_date.strftime("%F"), disabled: true %>
                                </div>
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="form-group">
                                <div class="form-field">
                                  <span> <%= t ".end_date" %> </span>
                                  <%= date_field :end_date, "", class: "form-control", value: @tour.end_date.strftime("%F"), disabled: true %>
                                </div>
                              </div>
                            </div>
                            <%= render "booking" if current_user&.activated? %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <%= render "reviews/form" if current_user %>
          </div>
          <div class="row">
            <div id="container">
              <%= render @reviews %>
            </div>
            <div class="col-sm-12">
              <hr>
              <div id="pagy_container">
                <%== pagy_bootstrap_nav_js @pagy %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tours/show.js.erb
$('#container').html("<%= j render @reviews %>");
$('#pagy_container').html('"<%== pagy_bootstrap_nav_js @pagy %>"');
Pagy.init(document.getElementById('container'));
Pagy.init(document.getElementById('pagy_container'));