config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only: %i(new create)
    resources :tours, only: %i(index show)
    resources :tour_requests, except: %i(new show edit)
    resources :reviews, only: :create
    namespace :admin do
      resources :users, only: %i(index edit update destroy)
      resources :tours
      resources :reviews
      resources :tour_requests
      resources :requests_histories
      get "/axlsx_index", to: "axlsx#index"
      resources :notifications
      get "/filter_ajax", to: "notifications#filter_ajax"
      resources :filter_tours, only: %i(index)
    end
    get "/authorization/:id", to: "authorizations#edit", as: :authorization
    post "/authorization/:id", to: "authorizations#update",
                               as: :authorization_activate
    mount ActionCable.server => "/cable"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {admin: 0, user: 1}

  devise :omniauthable, omniauth_providers: [:google_oauth2]

  before_save :downcase_email

  has_many :reviews, dependent: :destroy
  has_many :tour_requests, dependent: :destroy
  has_many :notifications, dependent: :destroy

  UPDATABLE_ATTRS = %i(name email password password_confirmation).freeze

  validates :activated, presence: true
  validates :name, presence: true, length: {maximum: Settings.user.name_max}
  validates :email, presence: true, length: {maximum: Settings.user.email_max},
                    format: {with: Settings.user.email_regex},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true,
                       length: {minimum: Settings.user.pass_min},
                       allow_nil: true
  has_secure_password

  scope :lastest, ->{order(created_at: :desc)}

  def self.from_omniauth access_token
    data = access_token.info
    user = User.where(email: data["email"]).first
    user || user = User.create(name: data["name"],
                               email: data["email"],
                               password: Devise.friendly_token[0, 20],
                               uid: access_token[:uid],
                               provider: access_token[:provider])
    user
  end

  private
  def downcase_email
    email.downcase!
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "layouts/application_admin"
  before_action :logged_in_user
  before_action :check_admin
  before_action :load_user, except: %i(index)

  def index
    @pagy, @users = pagy(User.all.lastest, items: Settings.user.per_page)
  end

  def show; end

  def edit; end

  def update
    if @user.update user_params
      success_format t ".update_success"
    else
      danger_format t ".update_failed"
    end
  end

  def destroy
    total = User.all.count
    index = User.all.find_index(@user)
    if @user.destroy
      cur_page = handle_page total, index
      @pagy, @users = pagy(User.all.lastest, items: Settings.user.per_page,
                            page: cur_page)
      success_format t ".destroy_success"
    else
      danger_format t ".destroy_danger"
    end
  end

  private

  def handle_page total, index
    cur_page = (((total - index) - 1) / Settings.user.per_page).ceil + 1

    users = User.limit(Settings.user.per_page).offset(
      Settings.user.per_page * (cur_page - 1)
    )
    cur_page -= 1 if users.empty?
    cur_page
  end

  def load_user
    flash[:success] = t "admin.users.show.show_user_success"
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t "admin.users.show.show_user_failed"
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit User::UPDATABLE_ATTRS
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      session["user_id"] = @user.id
      redirect_to root_path
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
                                             .except(:extra)
      redirect_to signup_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t ".user_registering_successful"
      redirect_to root_url
    else
      flash.now[:danger] = t ".user_not_saved"
      render :new
    end
  end

  def new
    @user = User.new
  end
end

app/views/admin/users/_form.html.erb
<div class="col-12">
  <%= form_for [:admin, @user], remote: true do |f| %>
    <%= render "layouts/error_messages", object: f.object %>
    <div class="col-12">
      <div class="content">
        <div class="row">
          <div class="col-md-4">
            <div class="card card-user">
              <div class="image">
              </div>
              <div class="card-body">
                <div class="author">
                  <div class="row form-group">
                    <div class="col-md-12">
                      <img
                      src="https://bootdey.com/img/Content/avatar/avatar7.png"
                      alt="">
                        <img class="tour__preview" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card card-user">
                <div class="card-header">
                  <h5 class="card-title"><%= t ".user_form_preview" %></h5>
                </div>
                <div class="card-body">
                  <form>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label t(".name") %>
                          <%= f.text_field :name, class: "form-control", placeholder: "Your name" %>
                        </div>
                      </div>
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label t(".email") %>
                          <%= f.email_field :email, class: "form-control", placeholder: "Your email" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6 pr-1">
                        <div class="form-group">
                          <%= f.label t(".password") %>
                          <%= f.password_field :password, class: "form-control", placeholder: "Your password" %>
                        </div>
                      </div>
                      <div class="col-md-6 pl-1">
                        <div class="form-group">
                          <%= f.label t(".password_confirm") %>
                          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Your password" %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="update ml-auto mr-auto">
                        <%= f.submit yield(:button_text), class: "btn btn-primary" %>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <td>
    <img
        src="https://bootdey.com/img/Content/avatar/avatar7.png"
        alt="">
    </td>
    <td>
      <%= user.name %>
    </td>
    <td>
      <%= user.email %>
    </td>
    <td>
      <%= user.role %>
    </td>
    <td>
      <%= link_to edit_admin_user_url(user.id) do %>
        <i class="nc-icon nc-ruler-pencil text-success m-2"></i>
      <% end %>
    <%= link_to admin_user_path(user.id), method: :delete, data: {confirm: t(".delete")}, class: "text-danger", remote: true do %>
      <i class="nc-icon nc-simple-remove text-danger"></i>
    <% end %>
  </td>
</tr>

app/views/admin/users/destroy.js.erb
$('#flash').html('<%= j render "layouts/flash_messages", flash: flash %> ');
$('#list_users').html('<%= j render @users %>');
$('#list_users_pagy').html('<%== pagy_bootstrap_nav(@pagy) %>');

app/views/admin/users/edit.html.erb
<% provide(:button_text, t(".button_text")) %>
<%= render "form" %>

app/views/admin/users/index.html.erb
<div class="col-md-12">
  <div class="list-user">
    <div class="card card-plain">
      <div class="card-header">
        <h4 class="card-title"> <%= t".list_users" %></h4>
        <p class="card-category"> <%= t".details" %></p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th><%= t ".avatar" %></th>
              <th>
                <%= t ".name" %>
              </th>
              <th>
                <%= t ".email" %>
              </th>
              <th>
                <%= t ".activated" %>
              </th>
              <th>
                <%= t ".role" %>
              </th>
              <th>
                <%= t ".action" %>
              </th>
            </thead>
            <tbody id="list_users">
              <%= render @users %>
            </tbody>
          </table>
          <div id="list_users_pagy">
            <%== pagy_bootstrap_nav @pagy %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/update.js.erb
$('#flash').html('<%= j render "layouts/flash_messages", flash: flash %> ');
<% provide(:button_text, t(".edit")) %>
$('#tour_form').html('<%= j render "form" %>');